# Generated by Django 3.2.12 on 2022-04-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlparser', '0002_rename_rawzip_rawarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawarchive',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
